# Jekyll Configuration
title: Michele Mattioni
tagline: Computational Neuroscientist · Engineer · Maker
author:
  name: Michele Mattioni
  email: mattions@gmail.com
  github: mattions
  twitter: mattions

permalink: /:categories/:year/:month/:day/:title
highlighter: rouge

# Site URL
url: "https://mattions.github.io"
baseurl: ""

# Exclude
exclude:
  - README.md
  - Rakefile
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
